apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: "operator-metering"
  namespace: openshift-metering  
spec:
  storage:
    type: "hive"
    hive:
      type: "sharedPVC"
      sharedPVC:
        claimName: "metering-pvc"
  hive:
    spec:
      metastore:
        storage:
          size: "5Gi"
          class: "rook-ceph-block-internal"