apiVersion: metering.openshift.io/v1
kind: Report
metadata:
  name: pod-cpu-request-hourly
  namespace: openshift-metering  
spec:
  query: "pod-cpu-request"
  schedule:
    period: "weekly"
  runImmediately: true
  reportingStart: "2019-01-01T00:00:00Z"
  reportingEnd: "2019-12-31T00:00:00Z"