apiVersion: v1
kind: PersistentVolume
metadata:
  name: metering-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  nfs:
    path: /data/metering
    server: 10.16.20.193
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: metering-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metering-pvc
  namespace: openshift-metering
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: metering-pvc